[package]
name = "choose"
version = "0.1.0"
authors = ["nathom <nathanthomas707@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
